StudnetsGrade/StudnetsGrade.Web/Controllers/GradeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Autofac;
using Microsoft.AspNetCore.Mvc;
using StudnetsGrade.Web.Models;

namespace StudnetsGrade.Web.Controllers
{
    public class GradeController : Controller
    {
        public IActionResult Index()
        {
            var model = Startup.AutofacContainer.Resolve<GradeModel>();
            var grades = model.GetAllGrades();
            return View(grades);
        }

        public IActionResult Create()
        {
            var model = new CreateGradeModel();
            return View(model);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create(CreateGradeModel model)
        {
            if (ModelState.IsValid)
            {
                try
                {
                    model.CreateGrade();
                    return RedirectToAction("Index");
                }
                catch (Exception)
                {
                    return View(model);
                }
            }
            return View(model);
        }
    }
}

StudnetsGrade/StudnetsGrade.Web/Views/Grade/Create.cshtml
@model StudnetsGrade.Web.Models.CreateGradeModel

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>CreateGradeModel</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-controller="Grade" asp-action="Create" method="post">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="StudentId" class="control-label"></label>
                <select asp-for="StudentId" asp-items="@Model.GetStudentList()" class="form-control">
                    <option>Please Select One</option>
                </select>
                @*<input asp-for="StudentId" class="form-control" />*@
                <span asp-validation-for="StudentId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="SubjectId" class="control-label"></label>
                <select asp-for="SubjectId" asp-items="@Model.GetSubjectList()" class="form-control">
                    <option>Please Select One</option>
                </select>
                @*<input asp-for="SubjectId" class="form-control" />*@
                <span asp-validation-for="SubjectId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="GradeValue" class="control-label"></label>
                <input asp-for="GradeValue" class="form-control" />
                <span asp-validation-for="GradeValue" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

StudnetsGrade/StudnetsGrade.Web/Views/Grade/Index.cshtml
@model IEnumerable<StudnetsGrade.Web.Models.GradeModel>

@{
    ViewData["Title"] = "Index";
}

<h1>Index</h1>

<p>
    <a asp-action="Create">Create New</a>
</p>

<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Student)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Subject)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.GradeValue)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.Student.Name)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Subject.Name)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.GradeValue)
                </td>
                <td>
                    @Html.ActionLink("Edit", "Edit", new { item.Id }) |
                    @Html.ActionLink("Details", "Details", new { item.Id }) |
                    @Html.ActionLink("Delete", "Delete", new { item.Id })
                </td>
            </tr>
        }
    </tbody>
</table>